{% set name = "ligo-lvalert" %}
{% set version = "1.5.6" %}
{% set sha256 = "43a18d76f60592a4bf39b9b1be5a64ce70a7e45fc746e04d9f499f79390cb59b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - lvalert = ligo.lvalert.tool:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - ligo-common
    - sleekxmpp
    - dnspython
    - numpy

test:
  imports:
    - ligo.lvalert
    - ligo.lvalert.tool
    - ligo.lvalert.utils
    - ligo.lvalert.version
  commands:
    - lvalert --help

about:
  home: https://wiki.ligo.org/DASWG/LVAlert
  dev_url: https://git.ligo.org/lscsoft/lvalert
  license: GPLv2+
  license_family: GPL
  license_file: COPYING
  summary: LVAlert Client Tools
  description: |
    LVAlert is an XMPP-based alert system. This package provides client
    tools for interacting with the LVAlert jabber server.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - tprestegard
    - aepace
