travis:
  secure:
    BINSTAR_TOKEN: jwcC61oI6CEsvidwofy5fEk6GCdHPS432X0+zAAjGJakNpe+cOL1WPVaXFAGCoarfiv1TMzcvRdU9j1zSPjWaaHdkPWhOfMtu/DiW2l8iVFARDIHuQFwBY4tPWn1iSip5HEUiAp/YhnmYRUm3f2tcN0av8m9LcAKwEkQzdKuhRyWE2O2AAkqBwJlPYq5lrhoxw8ZvSb9tC/Zd/xnmz3a1pcwCDBfKAB3A07VGN9nRWg1/QNAUGOD+vnoCQB9fe/sT8DUfYIujemqMF0TA8Lj0wyPKrn5ARMZg7ZloxkPzgij9W5mG6h6i8sJ92KsBbReh6EgIfVVALkqKcA3wuUvMWaSABSC0cQeUkO7m2aBiVpU0E+CUJjsyWqe0WmbZbjtSHDLOqFMThlczuG57PRp2KiiwQXsA0zbDNr78khYjD+WRPNtRjRug1dhFJVtmEv8KYS15fRgmNMr5WyZ6JO+AgNMOPw8FVIYUFRSvV58KE7hqqSEaQnQ05jPL7+zwU16TEiZueesWEvVFBr230Baf741pKR1rx+fp8LUDRsjOjPB0pnW8kgh/DEHQQH4mwAhx7XQIJMsJaHSuxRYomYiNbhHdkDaq6LOy9QafBeXAuV5v676u5qeCXamlfDFyef7k+2IX3JCIcYQ0lqIYQ9RMq0opDEaT4prEbZxudRXOT0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
